week11_chap11_12_13/config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
    resources :microposts, only: %i[create destroy]
  end
end

week11_chap11_12_13/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

week11_chap11_12_13/app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :content, presence: true,
    length: {maximum: Settings.maximum_post_length}
  validate :picture_size

  scope :created_at_desc, ->{order created_at: :desc}

  mount_uploader :picture, PictureUploader

  private

  def picture_size
    settings_size = Settings.standard_memory.megabytes
    errors.add :picture, t(".picture_size") if picture.size > settings_size
  end
end

week11_chap11_12_13/app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  attr_reader :remember_token

  has_many :microposts, dependent: :destroy

  validates :email, presence: true,
    length: {maximum: Settings.maximum_email_length},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}

  validates :name,  presence: true,
    length: {maximum: Settings.maximum_name_length}

  validates :password, presence: true,
    length: {minimum: Settings.minimum_password_length},
    allow_nil: true

  before_save :email_downcase

  has_secure_password

  class << self
    def digest string
      if cost = ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    @remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated? remember_token
    return false unless remember_digest
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def current_user? user
    self == user
  end

  private
  def email_downcase
    email.downcase!
  end
end

week11_chap11_12_13/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end

  def logged_in_user
    return if logged_in?
    store_location
    flash[:danger] = t "controllers.users.logged_in_user.message"
    redirect_to login_url
  end
end

week11_chap11_12_13/app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: %i(create destroy)
  before_action :correct_user, only: :destroy

  def create
    @micropost = current_user.microposts.new(micropost_params)
    if @micropost.save
      flash[:success] = t "controllers.microposts.create.succeed"
      redirect_to root_url
    else
      @feed_items = current_user.microposts.created_at_desc.paginate page:
        params[:page], per_page: Settings.per_page
      render "static_pages/home"
    end
  end

  def destroy
    if @micropost.destroy
      flash[:success] = t "controllers.microposts.destroy.succeed"
      redirect_to request.referrer || root_url
    else
      flash[:danger] = t "controllers.microposts.destroy.fail"
      redirect_to root_url
    end
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :picture)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.blank?
  end
end

week11_chap11_12_13/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase

    if user&.authenticate(params[:session][:password])
      logged_user user
    else
      flash.now[:danger] = t "controllers.sessions.error_messages"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

week11_chap11_12_13/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    return unless logged_in?
    @micropost  = current_user.microposts.build
    @feed_items = current_user.microposts.created_at_desc.paginate page:
      params[:page], per_page: Settings.per_page
  end

  def help; end

  def about; end

  def contact; end
end

week11_chap11_12_13/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: %i(show edit destroy)
  before_action :logged_in_user, only: %i(index edit destroy)
  before_action :correct_user, only: %i(edit update)
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate page: params[:page], per_page: Settings.per_page
  end

  def show
    @microposts = @user.microposts.paginate page: params[:page]
    return if @user
    flash[:danger] = t "controllers.users.show.message"
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      log_in @user
      flash[:success] = t "users.new.u_message"
      redirect_to @user
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = t ".message"
      redirect_to @user
    else
      flash[:danger] = t "controllers.users.show.message"
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t "controllers.users.destroy.message"
      redirect_to users_url
    else
      flash[:danger] = t "controllers.users.show.message"
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
      :password_confirmation, :admin)
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end

  def correct_user
    return if current_user.current_user?(@user)
    flash[:danger] = t "controllers.users.correct_user.message"
    redirect_to edit_user_path(current_user)
  end

  def find_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = t ".cannot_find_user"
    redirect_to root_url
  end
end

week11_chap11_12_13/app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t("helpers.base_title")
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

week11_chap11_12_13/app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by id: user_id
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by id: user_id
      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    current_user
  end

  def logged_user user
    log_in user
    remember_me = params[:session][:remember_me]
    remember_me == Settings.remember_yes ? remember(user) : forget(user)
    redirect_back_or user
  end

  def forget user
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete :user_id
    @current_user = nil
  end

  def redirect_back_or default
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

week11_chap11_12_13/app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, size: Settings.ava_size
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

week11_chap11_12_13/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small><%= t(".info").html_safe%></small>
  <nav>
    <ul>
      <li><%= link_to t("static_pages.about.name"), about_path %></li>
      <li><%= link_to t("static_pages.contact.name"), contact_path %></li>
      <li><a href="http://news.railstutorial.org/"><%=t(".new")%></a></li>
    </ul>
  </nav>
</footer>

week11_chap11_12_13/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".sample_app"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("static_pages.home.name"), root_path %></li>
        <li><%= link_to t("static_pages.help.name"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t(".users"), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t ".acc" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".setting"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".login"), login_path %></li>
        <% end %>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             <%=icon('fas','globe-asia')%> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".lang.en"), locale: "en" %></li>
              <li><%= link_to t(".lang.vi"), locale: "vi" %></li>
            </ul>
          </li>
      </ul>
    </nav>
  </div>
</header>

week11_chap11_12_13/app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

week11_chap11_12_13/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
<![endif]-->

week11_chap11_12_13/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title%> </title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
      <% end %>
      <%= yield%>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

week11_chap11_12_13/app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: Settings.m_ava_size), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    <%= t ".time_1" %> <%= time_ago_in_words(micropost.created_at) %>
    <%= t ".time_2" %>
    <% if current_user.current_user? micropost.user %>
      <%= link_to t(".delete"), micropost, method: :delete,
        data: {confirm: t(".confirm")} %>
    <% end %>
  </span>
</li>

week11_chap11_12_13/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
     <%= t(".content") %> <%= pluralize(object.errors.count, t(".err")) %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

week11_chap11_12_13/app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

week11_chap11_12_13/app/views/shared/_micropost_form.html.erb
<%= form_with model: @micropost, local: true do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: t(".content") %>
  </div>
  <%= f.submit t(".post"), class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

week11_chap11_12_13/app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: Settings.m_ava_size),
  current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t(".view"), current_user %></span>
<span><%= pluralize(current_user.microposts.count, t(".post")) %></span>

week11_chap11_12_13/app/views/users/_form.html.erb
<%= form_with model: @user, url: yield(:path_text), local: true do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name, t(".u_name") %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email, t(".u_email") %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password, t(".u_pass") %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, t(".u_pass_cf") %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

week11_chap11_12_13/app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: Settings.ava_size %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user.current_user?(user) %>
    | <%= link_to t(".delete"), user, method: :delete,
      data: { confirm: t(".confirm") } %>
  <% end %>
</li>

week11_chap11_12_13/app/views/users/edit.html.erb
<% provide :title, t(".name") %>
<% provide :button_text, t(".u_save") %>
<% provide :path_text, user_path(current_user) %>
<h1><%= yield :title %> </h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" rel="noopener" target="_blank">
        <%= t ".u_ava" %></a>
    </div>
  </div>
</div>

week11_chap11_12_13/app/views/users/index.html.erb
<% provide :title, t(".name") %>
<h1><%= yield :title %> </h1>

<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</ul>
<%= will_paginate %>

week11_chap11_12_13/app/views/users/new.html.erb
<% provide :title, t(".name") %>
<% provide :button_text, t(".u_create") %>
<% provide :path_text, signup_path %>
<h1><%= yield :title %> </h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

week11_chap11_12_13/app/views/users/show.html.erb
<% provide :title, @user.name%>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.microposts.any? %>
    <h3> <%= t ".name" %> (<%= @user.microposts.count %>)</h3>
    <ol class="microposts">
      <%= render @microposts %>
    </ol>
    <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>